[package]
name = "sqlc-derive"
version = "0.4.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
postgres-types = "0.2.8"
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.77"

[features]
# default = ["with-postgres"]
with-postgres = []
with-tokio-postgres = []
with-deadpool = []
