/// @generated by the sqlc-gen-rust on sqlc-generate using sqlc.yaml
/// DO NOT EDIT.
const GET_AUTHOR: &str = r#"
SELECT id, uuid, name, bio, data, ip_inet, ip_cidr, mac_address, created_at, updated_at FROM authors
WHERE id = $1 LIMIT 1
"#;
const LIST_AUTHORS: &str = r#"
SELECT id, uuid, name, bio, data, ip_inet, ip_cidr, mac_address, created_at, updated_at FROM authors
ORDER BY name
"#;
const CREATE_AUTHOR: &str = r#"
INSERT INTO authors (
          name, bio
) VALUES (
  $1, $2
)
RETURNING id, uuid, name, bio, data, ip_inet, ip_cidr, mac_address, created_at, updated_at
"#;
const DELETE_AUTHOR: &str = r#"
DELETE FROM authors
WHERE id = $1
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct Author {
    pub id: i64,
    pub uuid: Option<uuid::Uuid>,
    pub name: String,
    pub bio: Option<String>,
    pub data: Option<serde_json::Value>,
    pub ip_inet: cidr::IpInet,
    pub ip_cidr: cidr::IpInet,
    pub mac_address: eui48::MacAddress,
    pub created_at: time::OffsetDateTime,
    pub updated_at: time::OffsetDateTime,
}
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct CreateAuthorParams {
    pub name: String,
    pub bio: Option<String>,
}
pub struct Queries {
    client: tokio_postgres::Client,
}
impl Queries {
    pub fn new(client: tokio_postgres::Client) -> Self {
        Self { client }
    }
    pub(crate) async fn create_author(
        &mut self,
        arg: CreateAuthorParams,
    ) -> Result<Author, sqlc_core::Error> {
        let row = self.client.query_one(CREATE_AUTHOR, &[&arg.name, &arg.bio]).await?;
        Ok(sqlc_core::FromPostgresRow::from_row(&row)?)
    }
    pub(crate) async fn delete_author(
        &mut self,
        id: i64,
    ) -> Result<(), sqlc_core::Error> {
        self.client.execute(DELETE_AUTHOR, &[&id]).await?;
        Ok(())
    }
    pub(crate) async fn get_author(
        &mut self,
        id: i64,
    ) -> Result<Author, sqlc_core::Error> {
        let row = self.client.query_one(GET_AUTHOR, &[&id]).await?;
        Ok(sqlc_core::FromPostgresRow::from_row(&row)?)
    }
    pub(crate) async fn list_authors(
        &mut self,
    ) -> Result<Vec<Author>, sqlc_core::Error> {
        let rows = self.client.query(LIST_AUTHORS, &[]).await?;
        let mut result: Vec<Author> = vec![];
        for row in rows {
            result.push(sqlc_core::FromPostgresRow::from_row(&row)?);
        }
        Ok(result)
    }
}
