/// @generated by the sqlc-gen-rust on sqlc-generate using sqlc.yaml
/// DO NOT EDIT.
use postgres::{Error, Row};
#[derive(Debug, Display)]
pub enum BookType {
    Fiction,
    Nonfiction,
}
const GET_AUTHOR: &str = r#"
select author_id, name, biography
from authors
where author_id = $1
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct GetAuthorParams {
    pub author_id: i32,
}
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct GetAuthorRow {
    pub author_id: i32,
    pub name: String,
    pub biography: Option<serde_json::Value>,
}
pub struct Queries {
    client: postgres::Client,
}
impl Queries {
    pub fn new(client: postgres::Client) -> Self {
        Self { client }
    }
    pub(crate) fn get_author(
        &mut self,
        params: GetAuthorParams,
    ) -> anyhow::Result<GetAuthorRow> {
        let row = self.client.query_one(GET_AUTHOR, &[&params.author_id])?;
        Ok(sqlc_core::FromPostgresRow::from_row(&row)?)
    }
}
