/// @generated by the sqlc-gen-rust on sqlc-generate using sqlc.yaml
/// DO NOT EDIT.
pub(crate) const DELETE_BOOK: &str = r#"
delete from books
where book_id = $1
"#;
#[derive(postgres_derive::ToSql, postgres_derive::FromSql)]
#[postgres(name = "book_type")]
pub enum BookType {
    #[postgres(name = "FICTION")]
    Fiction,
    #[postgres(name = "NONFICTION")]
    Nonfiction,
}
#[derive(sqlc_core::PostgresRow, sqlc_core::PostgresParams)]
pub struct Author {
    pub author_id: i32,
    pub name: String,
    pub biography: Option<serde_json::Value>,
}
#[derive(sqlc_core::PostgresRow, sqlc_core::PostgresParams)]
pub struct Book {
    pub book_id: i32,
    pub author_id: i32,
    pub isbn: String,
    pub book_type: BookType,
    pub title: String,
    pub year: i32,
    pub available: time::OffsetDateTime,
    pub tags: Vec<String>,
}
pub async fn delete_book<'a, C, I>(
    client: &'a C,
    book_id_list: I,
) -> sqlc_core::Result<sqlc_core::BatchStream<()>>
where
    C: sqlc_core::DBTX,
    I: IntoIterator + Send + 'a,
    I::IntoIter: Send,
    I::Item: std::borrow::Borrow<i32> + Send + 'a,
    <I as IntoIterator>::IntoIter: Send,
{
    client.batch_execute(DELETE_BOOK, book_id_list).await
}
