/// @generated by the sqlc-gen-rust on sqlc-generate using sqlc.yaml
/// DO NOT EDIT.
use postgres::{Error, Row};
#[derive(Debug, Display)]
pub enum Status {
    Open,
    Closed,
}
const LIST_CITIES: &str = r#"
select slug, name
from city
order by name
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct ListCitiesRow {
    pub slug: String,
    pub name: String,
}
const GET_CITY: &str = r#"
select slug, name
from city
where slug = $1
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct GetCityParams {
    pub slug: String,
}
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct GetCityRow {
    pub slug: String,
    pub name: String,
}
const CREATE_CITY: &str = r#"
INSERT INTO city (
    name,
    slug
) VALUES (
    $1,
    $2
) RETURNING slug, name
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct CreateCityParams {
    pub name: String,
    pub slug: String,
}
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct CreateCityRow {
    pub slug: String,
    pub name: String,
}
const UPDATE_CITY_NAME: &str = r#"
UPDATE city
SET name = $2
WHERE slug = $1
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct UpdateCityNameParams {
    pub slug: String,
    pub name: String,
}
const LIST_VENUES: &str = r#"
SELECT id, status, statuses, slug, name, city, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE city = $1
ORDER BY name
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct ListVenuesParams {
    pub city: String,
}
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct ListVenuesRow {
    pub id: i32,
    pub status: String,
    pub statuses: Option<Vec<String>>,
    pub slug: String,
    pub name: String,
    pub city: String,
    pub spotify_playlist: String,
    pub songkick_id: Option<String>,
    pub tags: Option<Vec<String>>,
    pub created_at: String,
}
const DELETE_VENUE: &str = r#"
DELETE FROM venue
WHERE slug = $1 AND slug = $1
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct DeleteVenueParams {
    pub slug: String,
}
const GET_VENUE: &str = r#"
SELECT id, status, statuses, slug, name, city, spotify_playlist, songkick_id, tags, created_at
FROM venue
WHERE slug = $1 AND city = $2
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct GetVenueParams {
    pub slug: String,
    pub city: String,
}
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct GetVenueRow {
    pub id: i32,
    pub status: String,
    pub statuses: Option<Vec<String>>,
    pub slug: String,
    pub name: String,
    pub city: String,
    pub spotify_playlist: String,
    pub songkick_id: Option<String>,
    pub tags: Option<Vec<String>>,
    pub created_at: String,
}
const CREATE_VENUE: &str = r#"
INSERT INTO venue (
    slug,
    name,
    city,
    created_at,
    spotify_playlist,
    status,
    statuses,
    tags
) VALUES (
    $1,
    $2,
    $3,
    NOW(),
    $4,
    $5,
    $6,
    $7
) RETURNING id
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct CreateVenueParams {
    pub slug: String,
    pub name: String,
    pub city: String,
    pub spotify_playlist: String,
    pub status: String,
    pub statuses: Option<Vec<String>>,
    pub tags: Option<Vec<String>>,
}
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct CreateVenueRow {
    pub id: i32,
}
const UPDATE_VENUE_NAME: &str = r#"
UPDATE venue
SET name = $2
WHERE slug = $1
RETURNING id
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct UpdateVenueNameParams {
    pub slug: String,
    pub name: String,
}
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct UpdateVenueNameRow {
    pub id: i32,
}
const VENUE_COUNT_BY_CITY: &str = r#"
SELECT
    city,
    count(*)
FROM venue
GROUP BY 1
ORDER BY 1
"#;
#[derive(Clone, Debug, sqlc_derive::FromPostgresRow, PartialEq)]
pub(crate) struct VenueCountByCityRow {
    pub city: String,
    pub count: i64,
}
pub struct Queries {
    client: postgres::Client,
}
impl Queries {
    pub fn new(client: postgres::Client) -> Self {
        Self { client }
    }
    pub(crate) fn list_cities(&mut self) -> anyhow::Result<Vec<ListCitiesRow>> {
        let rows = self.client.query(LIST_CITIES, &[])?;
        let mut result: Vec<ListCitiesRow> = vec![];
        for row in rows {
            result.push(sqlc_core::FromPostgresRow::from_row(&row)?);
        }
        Ok(result)
    }
    pub(crate) fn get_city(
        &mut self,
        params: GetCityParams,
    ) -> anyhow::Result<GetCityRow> {
        let row = self.client.query_one(GET_CITY, &[&params.slug])?;
        Ok(sqlc_core::FromPostgresRow::from_row(&row)?)
    }
    pub(crate) fn create_city(
        &mut self,
        params: CreateCityParams,
    ) -> anyhow::Result<CreateCityRow> {
        let row = self.client.query_one(CREATE_CITY, &[&params.name, &params.slug])?;
        Ok(sqlc_core::FromPostgresRow::from_row(&row)?)
    }
    pub(crate) fn update_city_name(
        &mut self,
        params: UpdateCityNameParams,
    ) -> anyhow::Result<()> {
        self.client.execute(UPDATE_CITY_NAME, &[&params.slug, &params.name])?;
        Ok(())
    }
    pub(crate) fn list_venues(
        &mut self,
        params: ListVenuesParams,
    ) -> anyhow::Result<Vec<ListVenuesRow>> {
        let rows = self.client.query(LIST_VENUES, &[&params.city])?;
        let mut result: Vec<ListVenuesRow> = vec![];
        for row in rows {
            result.push(sqlc_core::FromPostgresRow::from_row(&row)?);
        }
        Ok(result)
    }
    pub(crate) fn delete_venue(
        &mut self,
        params: DeleteVenueParams,
    ) -> anyhow::Result<()> {
        self.client.execute(DELETE_VENUE, &[&params.slug])?;
        Ok(())
    }
    pub(crate) fn get_venue(
        &mut self,
        params: GetVenueParams,
    ) -> anyhow::Result<GetVenueRow> {
        let row = self.client.query_one(GET_VENUE, &[&params.slug, &params.city])?;
        Ok(sqlc_core::FromPostgresRow::from_row(&row)?)
    }
    pub(crate) fn create_venue(
        &mut self,
        params: CreateVenueParams,
    ) -> anyhow::Result<CreateVenueRow> {
        let row = self
            .client
            .query_one(
                CREATE_VENUE,
                &[
                    &params.slug,
                    &params.name,
                    &params.city,
                    &params.spotify_playlist,
                    &params.status,
                    &params.statuses,
                    &params.tags,
                ],
            )?;
        Ok(sqlc_core::FromPostgresRow::from_row(&row)?)
    }
    pub(crate) fn update_venue_name(
        &mut self,
        params: UpdateVenueNameParams,
    ) -> anyhow::Result<UpdateVenueNameRow> {
        let row = self
            .client
            .query_one(UPDATE_VENUE_NAME, &[&params.slug, &params.name])?;
        Ok(sqlc_core::FromPostgresRow::from_row(&row)?)
    }
    pub(crate) fn venue_count_by_city(
        &mut self,
    ) -> anyhow::Result<Vec<VenueCountByCityRow>> {
        let rows = self.client.query(VENUE_COUNT_BY_CITY, &[])?;
        let mut result: Vec<VenueCountByCityRow> = vec![];
        for row in rows {
            result.push(sqlc_core::FromPostgresRow::from_row(&row)?);
        }
        Ok(result)
    }
}
